#!/usr/bin/env bash
# =============================================================================
# Migration script: Build new WASM and install on network
# =============================================================================
#
# @title Build and install WASM
# @notice Builds the payroll contract WASM and installs it on the network.
# @dev    Writes NEW_WASM_HASH to scripts/migrations/.env.migration. Do not commit.
#
# Usage:
#   ./scripts/migrations/02_build_and_install_wasm.sh
#
# Environment:
#   SOURCE_ACCOUNT (recommended) Secret key or identity for install.
#   NETWORK        (optional) testnet | mainnet | futurenet. Default: testnet.
#   RPC_URL        (optional) Soroban RPC URL.
#
# Exit: 0 on success; 1 on build/install failure or missing WASM.
# =============================================================================
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
CONTRACT_CRATE="$REPO_ROOT/onchain/contracts/stello_pay_contract"
NETWORK="${NETWORK:-testnet}"
RPC_URL="${RPC_URL:-https://soroban-testnet.stellar.org}"
SOURCE_ACCOUNT="${SOURCE_ACCOUNT:-}"

if [[ -z "$SOURCE_ACCOUNT" ]]; then
  echo "Warning: SOURCE_ACCOUNT not set. Install step may fail; set it for live install."
fi

# Detect CLI
CLI="stellar"
if ! command -v stellar &>/dev/null; then
  if command -v soroban &>/dev/null; then
    CLI="soroban"
  else
    echo "Error: Neither 'stellar' nor 'soroban' CLI found."
    exit 1
  fi
fi

echo "Building contract in $CONTRACT_CRATE"
cd "$CONTRACT_CRATE"
cargo build --target wasm32-unknown-unknown --release
"$CLI" contract build --verbose

WASM_PATH="$CONTRACT_CRATE/target/wasm32-unknown-unknown/release/stello_pay_contract.wasm"
if [[ ! -f "$WASM_PATH" ]]; then
  echo "Error: WASM not found at $WASM_PATH (run 'stellar contract build' or 'cargo build --target wasm32-unknown-unknown --release' in the contract crate)."
  exit 1
fi

echo "Installing WASM on network: $NETWORK"
INSTALL_ARGS=(
  --wasm "$WASM_PATH"
  --network "$NETWORK"
  --source-account "$SOURCE_ACCOUNT"
)
if [[ -n "$RPC_URL" ]]; then
  INSTALL_ARGS+=(--rpc-url "$RPC_URL")
fi

NEW_WASM_HASH=$("$CLI" contract install "${INSTALL_ARGS[@]}" 2>/dev/null || true)
if [[ -z "$NEW_WASM_HASH" ]]; then
  # Try without source-account for read-only hash (some CLIs support build only)
  NEW_WASM_HASH=$("$CLI" contract install --wasm "$WASM_PATH" --network "$NETWORK" ${RPC_URL:+--rpc-url "$RPC_URL"} 2>/dev/null || true)
fi

if [[ -z "$NEW_WASM_HASH" ]]; then
  echo "Error: Could not install WASM or get hash. Ensure SOURCE_ACCOUNT and network are correct."
  exit 1
fi

mkdir -p "$SCRIPT_DIR"
echo "# Generated by 02_build_and_install_wasm.sh - do not commit" > "$SCRIPT_DIR/.env.migration"
echo "export NEW_WASM_HASH=$NEW_WASM_HASH" >> "$SCRIPT_DIR/.env.migration"
echo "NEW_WASM_HASH=$NEW_WASM_HASH"
echo "Stored in $SCRIPT_DIR/.env.migration. Next: run 03_authorize_and_upgrade.sh \$NEW_WASM_HASH"
