#!/usr/bin/env python3
"""Per-crate line-coverage gate for StellopayCore Soroban contract crates.

Parses `cargo llvm-cov --json` reports and enforces a minimum line-coverage
percentage per contract crate under ``<workspace>/contracts/``.

The script is a *pure checker*: it does not run `cargo llvm-cov` itself. The
workflow (or the developer, locally) is responsible for generating the JSON
reports first. This separation keeps the gate fast to audit and lets GitHub
Actions report instrumentation/build failures distinctly from coverage
failures.

Design notes
------------
* Coverage is measured on ``src/`` files only (``contracts/<dir>/src/...``).
  Unit tests and integration tests drive that measurement; the files
  themselves are what counts toward the gate.
* In per-matrix mode (``--crate <name>``) only the named crate is checked, so
  a report generated by ``cargo llvm-cov -p <name>`` (which may also contain
  path-dependency sources) is filtered to the crate under test.
* In aggregate mode (no ``--crate``) *every* discovered contract crate must be
  present in the reports with measurable lines; a missing crate fails the
  gate. This prevents the matrix from silently skipping a crate.

Exit codes
----------
* ``0`` -- every checked crate meets the threshold.
* ``1`` -- a checked crate is below the threshold, has no coverage data, or
  the reports/workspace could not be read.
* ``2`` -- invalid command-line arguments.

Examples
--------
Check a single crate report (per-matrix job)::

    python3 tools/coverage_check/check_coverage.py \
        --workspace onchain \
        --report /tmp/coverage/rbac.json \
        --min-line-pct 95 \
        --crate rbac

Check an entire directory of per-crate reports (aggregate summary)::

    python3 tools/coverage_check/check_coverage.py \
        --workspace onchain \
        --report coverage-reports \
        --min-line-pct 95
"""

from __future__ import annotations

import argparse
import json
import os
import re
import sys
from pathlib import Path

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

DEFAULT_WORKSPACE = "onchain"
DEFAULT_MIN_LINE_PCT = 95.0
CONTRACTS_SUBDIR = "contracts"
SRC_MARKER = "/src/"

# Matches `name = "..."` in a Cargo.toml (package section).
_PACKAGE_NAME_RE = re.compile(r'^\s*name\s*=\s*"([^"]+)"\s*$', re.MULTILINE)


class CoverageGateError(Exception):
    """Raised when the gate cannot be evaluated (missing/malformed input)."""


# ---------------------------------------------------------------------------
# Crate discovery
# ---------------------------------------------------------------------------


def discover_contract_crates(workspace: str) -> list[dict]:
    """Discover contract crates under ``<workspace>/contracts/``.

    Returns a list of ``{"package": <Cargo package name>, "dir": <dir name>}``
    sorted by package name. Raises :class:`CoverageGateError` if the contracts
    directory is missing or a manifest has no parseable ``name``.
    """
    contracts_dir = Path(workspace) / CONTRACTS_SUBDIR
    if not contracts_dir.is_dir():
        raise CoverageGateError(
            f"workspace contracts dir not found: {contracts_dir}"
        )

    crates = []
    for manifest in sorted(contracts_dir.iterdir()):
        if not manifest.is_dir():
            continue
        cargo_toml = manifest / "Cargo.toml"
        if not cargo_toml.is_file():
            continue
        text = cargo_toml.read_text(encoding="utf-8")
        match = _PACKAGE_NAME_RE.search(text)
        if not match:
            raise CoverageGateError(
                f"cannot determine package name in {cargo_toml}"
            )
        crates.append({"package": match.group(1), "dir": manifest.name})

    if not crates:
        raise CoverageGateError(
            f"no contract crates found under {contracts_dir}"
        )
    return crates


# ---------------------------------------------------------------------------
# Report loading / parsing
# ---------------------------------------------------------------------------


def load_reports(report_arg: str) -> list[dict]:
    """Load one llvm-cov JSON report, or every ``*.json`` report in a directory."""
    path = Path(report_arg)
    if path.is_dir():
        files = sorted(p for p in path.iterdir() if p.suffix == ".json")
        if not files:
            raise CoverageGateError(f"no *.json reports found in {path}")
        return [load_report(p) for p in files]
    if path.is_file():
        return [load_report(path)]
    raise CoverageGateError(f"report path does not exist: {report_arg}")


def load_report(path: Path) -> dict:
    """Read and decode a single llvm-cov JSON export file."""
    try:
        with path.open(encoding="utf-8") as fh:
            return json.load(fh)
    except FileNotFoundError:
        raise CoverageGateError(f"report not found: {path}")
    except json.JSONDecodeError as exc:
        raise CoverageGateError(f"malformed JSON report {path}: {exc}")


def _as_int(value: object) -> int:
    """Coerce a JSON line-count value to ``int`` defensively."""
    if isinstance(value, bool):
        return int(value)
    if isinstance(value, int):
        return value
    if isinstance(value, float):
        return int(value)
    if isinstance(value, str):
        try:
            return int(value)
        except ValueError:
            pass
        try:
            return int(float(value))
        except ValueError:
            pass
    return 0


def _line_counts(file_entry: dict) -> tuple[int, int]:
    """Return ``(count, covered)`` lines for a single llvm-cov file entry.

    Missing summary sections are treated as zero so that files the
    instrumentation never executed still participate in the aggregate (they
    count as uncovered lines).
    """
    summary = file_entry.get("summary") or {}
    lines = summary.get("lines") or {}
    count = _as_int(lines.get("count", 0))
    covered = _as_int(lines.get("covered", 0))
    return count, covered


def iter_file_entries(report: dict):
    """Yield ``(filename, count, covered)`` for every file entry in a report."""
    for data in report.get("data") or []:
        for file_entry in data.get("files") or []:
            filename = file_entry.get("filename")
            if not filename:
                continue
            count, covered = _line_counts(file_entry)
            yield filename, count, covered


# ---------------------------------------------------------------------------
# Aggregation
# ---------------------------------------------------------------------------


def match_crate(filename: str, crates: list[dict]):
    """Return the crate whose ``contracts/<dir>/src/`` path matches, or ``None``.

    Both relative (``contracts/rbac/src/lib.rs``) and absolute
    (``/home/runner/.../onchain/contracts/rbac/src/lib.rs``) paths are handled,
    and Windows-style separators are normalized. The trailing ``/src/`` marker
    makes ``contracts/rbac/`` and ``contracts/rbac-interface/`` unambiguous.
    """
    norm = filename.replace("\\", "/")
    for crate in crates:
        marker = f"{CONTRACTS_SUBDIR}/{crate['dir']}{SRC_MARKER}"
        if marker in norm:
            return crate
    return None


def aggregate(reports: list[dict], crates: list[dict]) -> dict:
    """Aggregate per-crate line coverage across one or more reports.

    Returns ``{package: {"dir": ..., "total": int, "covered": int,
    "files": {filename: (covered, total)}}}``. When the same source file
    appears more than once (multiple reports or multiple data blocks), the
    measurement with the largest line total is kept, so a crate is never
    double-counted.
    """
    per_crate = {
        crate["package"]: {
            "dir": crate["dir"],
            "present": False,
            "total": 0,
            "covered": 0,
            "files": {},
        }
        for crate in crates
    }

    for report in reports:
        for filename, count, covered in iter_file_entries(report):
            crate = match_crate(filename, crates)
            if crate is None:
                continue
            entry = per_crate[crate["package"]]
            entry["present"] = True
            prev_covered, prev_total = entry["files"].get(filename, (0, 0))
            if count >= prev_total:
                entry["files"][filename] = (covered, count)

    for entry in per_crate.values():
        for covered, total in entry["files"].values():
            entry["total"] += total
            entry["covered"] += covered

    return per_crate


# ---------------------------------------------------------------------------
# Evaluation and rendering
# ---------------------------------------------------------------------------


def _failure_reason(total: int, present: bool, pct: float, min_pct: float) -> str:
    if not present:
        return "no coverage data (crate absent from reports)"
    if total == 0:
        return "no coverage data (0 measurable lines in src/)"
    return f"line coverage {pct:.2f}% below {min_pct:.2f}% threshold"


def evaluate(
    per_crate: dict,
    crates: list[dict],
    min_pct: float,
    only_crate: str | None = None,
) -> list[dict]:
    """Produce the per-crate gate results.

    With ``only_crate`` set, only that package is evaluated; otherwise every
    discovered contract crate must have data. A crate with no measurable lines
    (or entirely absent from the reports) is a hard failure.
    """
    if only_crate is not None:
        packages = [only_crate]
    else:
        packages = [crate["package"] for crate in crates]

    results = []
    for package in packages:
        entry = per_crate.get(package)
        if entry is None:
            results.append(
                {
                    "package": package,
                    "dir": None,
                    "total": 0,
                    "covered": 0,
                    "pct": 0.0,
                    "threshold": min_pct,
                    "status": "FAIL",
                    "reason": "no coverage data (crate absent from reports)",
                    "files": {},
                }
            )
            continue

        total = entry["total"]
        covered = entry["covered"]
        pct = (covered * 100.0 / total) if total > 0 else 0.0
        passed = total > 0 and pct >= min_pct
        results.append(
            {
                "package": package,
                "dir": entry["dir"],
                "total": total,
                "covered": covered,
                "pct": pct,
                "threshold": min_pct,
                "status": "PASS" if passed else "FAIL",
                "reason": None if passed else _failure_reason(total, entry["present"], pct, min_pct),
                "files": entry["files"],
            }
        )
    return results


def render_summary(results: list[dict], min_pct: float) -> str:
    """Render the per-crate gate results as a Markdown table.

    Failing crates additionally include a per-file breakdown so a developer
    can see exactly which source file is dragging the crate down.
    """
    lines = [
        "## Contract Coverage Gate",
        "",
        f"Minimum line coverage: {min_pct:.2f}% per contract crate (src/ only).",
        "",
        "| Package | Directory | Lines | Covered | Coverage % | Threshold % | Status |",
        "|---|---|---|---|---|---|---|",
    ]
    for result in results:
        pct = "—" if result["total"] == 0 else f"{result['pct']:.2f}%"
        lines.append(
            f"| {result['package']} | {result['dir'] or '—'} | "
            f"{result['total']} | {result['covered']} | {pct} | "
            f"{result['threshold']:.2f}% | {result['status']} |"
        )

    for result in sorted(results, key=lambda r: r["package"]):
        if result["status"] != "FAIL":
            continue
        lines.append("")
        lines.append(f"### {result['package']} — {result['reason']}")
        if not result["files"]:
            continue
        lines.append("")
        lines.append("| File | Lines | Covered | Coverage % |")
        lines.append("|---|---|---|---|")
        for filename in sorted(result["files"]):
            covered, total = result["files"][filename]
            if total == 0:
                lines.append(f"| {filename} | 0 | 0 | — |")
            else:
                pct = covered * 100.0 / total
                lines.append(
                    f"| {filename} | {total} | {covered} | {pct:.2f}% |"
                )

    return "\n".join(lines)


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description=(
            "Enforce a per-crate line-coverage gate for Soroban contract "
            "crates from cargo llvm-cov --json reports."
        ),
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
    )
    parser.add_argument(
        "--report",
        required=True,
        help="llvm-cov JSON report file, or a directory of *.json reports",
    )
    parser.add_argument(
        "--workspace",
        default=DEFAULT_WORKSPACE,
        help="Cargo workspace root containing contracts/",
    )
    parser.add_argument(
        "--min-line-pct",
        type=float,
        default=DEFAULT_MIN_LINE_PCT,
        help="minimum line coverage percentage per crate",
    )
    parser.add_argument(
        "--crate",
        default=None,
        help="only check this single package (per-matrix-job mode)",
    )
    args = parser.parse_args(argv)

    if not (0.0 < args.min_line_pct <= 100.0):
        parser.error(
            f"--min-line-pct must be in (0, 100], got {args.min_line_pct}"
        )

    try:
        crates = discover_contract_crates(args.workspace)
        reports = load_reports(args.report)
    except CoverageGateError as exc:
        print(f"coverage gate error: {exc}", file=sys.stderr)
        return 1

    if args.crate is not None:
        known = {crate["package"] for crate in crates}
        if args.crate not in known:
            parser.error(
                f"--crate {args.crate!r} is not a contract crate in "
                f"{args.workspace} (known: {', '.join(sorted(known))})"
            )

    per_crate = aggregate(reports, crates)
    results = evaluate(per_crate, crates, args.min_line_pct, only_crate=args.crate)

    summary = render_summary(results, args.min_line_pct)
    print(summary)
    print()

    failed = [r for r in results if r["status"] == "FAIL"]
    if failed:
        print(
            f"coverage gate FAILED: {len(failed)} of {len(results)} checked "
            f"crate(s) below {args.min_line_pct:.2f}% line coverage",
            file=sys.stderr,
        )
    else:
        print(
            f"coverage gate PASSED: all {len(results)} checked crate(s) "
            f">= {args.min_line_pct:.2f}% line coverage"
        )

    step_summary = os.environ.get("GITHUB_STEP_SUMMARY")
    if step_summary:
        try:
            with open(step_summary, "w", encoding="utf-8") as fh:
                fh.write(summary + "\n")
        except OSError as exc:
            print(
                f"warning: could not write GITHUB_STEP_SUMMARY: {exc}",
                file=sys.stderr,
            )

    return 0 if not failed else 1


if __name__ == "__main__":
    sys.exit(main())
